name: server
description: Sample Vania backend web application framework
version: 1.0.0

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  faker: ^2.1.0
  vania: ^0.3.2


dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
