name: server
description: Sample Vania backend web application framework
version: 1.0.0

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  mongo_dart: ^0.10.3
  vania: ^0.3.1


dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
